<a href="https://colab.research.google.com/github/tustus1022-ui/esaa/blob/main/hw_transcription2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 핸들링 - 판다스

판다스 : 파이썬에서 데이터 처리를 위해 존재하는 가장 인기 있는 라이브러리
- 행과 열로 이루어진 2차원 데이터를 효율적으로 가공/처리 가능한 기능 제공
- 넘파이 기반으로 작성됨. 넘파이보다 유연하고 편리하게 데이터 핸들링 가능
- 고수준 API 제공
- 내부 데이터(파이썬의 리스트, 컬렉션, 넘파이 등)뿐만 아니라 CSV 등의 파일을 쉽게 DataFrame으로 변경해 데이터의 가공/분석을 편리하게 수행 가능
- 핵심 객체 : DataFrame -> 여러 개의 행과 열로 이루어진 2차원 데이터를 담는 데이터 구조체

DataFrame
- Index : RDBMS의 PK처럼 개별 데이터를 고유하게 식별하는 Key 값
- Series와 DataFrame은 모두 Index를 Key값으로 가짐
- Series는 칼럼이 하나 뿐인 데이터 구조체, DataFrame은 칼럼이 여러 개인 데이터 구조체
- DataFrame은 여러 개의 Series로 이루어짐

#### 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

pandas를 pd로 alias해 임포트하는 것이 관례

In [24]:
import pandas as pd # 판다스 모듈 import

데이터 파일을 판다스의 DataFrame으로 로딩

사용할 데이터 파일은 캐글(Kaggle)에서 제공하는 타이타닉 탑승자 파일

해당 데이터의 train.csv 파일을 titanic_train.csv라는 파일명으로 변경해 다운로드

판다스 : 다양한 포맷으로 된 파일을 DataFrame으로 로딩할 수 있는 편리한 API 제공

=> read_csv(), read_table(), read_fwf()

- read_csv() : CSV(칼럼을 ','로 구분한 파일 포맷) 파일 포맷 변환을 위한 API.
어떤 필드 구분 문자 기반의 파일 포맷도 DataFrame으로 변환 가능 - read_csv()의 인자인 sep에 해당 구분 문자를 입력하면 됨
- read_csv()에서 sep 인자를 생략하면 자동으로 콤마 할당
- read_table() : 디폴트 필드 구분 문자는 탭('\t') 문자, read_csv()와 기능상 차이가 없음
- read_fwf() : Fixed Width, 고정 길이 기반의 칼럼 포맷을 DataFrame으로 로딩하기 위한 API

read_csv()


가장 중요한 인자 : filepath, 나머지 인자는 지정하지 않으면 디폴트 값으로 할당

Filepath에 로드하려는 데이터 파일의 경로를 포함한 파일명 입력, 파일명만 입력되면 파이썬 실행 파일이 있는 디렉터리와 동일한 디렉터리에 있는 파일명 로딩

In [25]:
titanic_df = pd.read_csv('titanic_train.csv')

In [26]:
# 맨 마지막에 titanic_df를 호출하면 DataFrame의 모든 데이터 출력
titanic_df = pd.read_csv('titanic_train.csv')
print('titanic 변수 type: ', type(titanic_df))
titanic_df

titanic 변수 type:  <class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

pd.read_csv()는 호출 시 파일명 인자로 들어온 파일을 로딩해 DataFrame 객체로 반환

read_csv()는 별다른 파라미터 지정이 없으면 파일의 맨 처음 로우를 칼럼명으로 인지하고 칼럼으로 변환, 콤마로 분리된 데이터값들이 해당 칼럼에 맞게 할당됨

파일에 기재되어있지 않는 데이터값이 로우 순으로 순차적으로 표시됨. 칼럼명도 표시되지 않는 데이터들은 판다스의 Index 객체 값. 모든 DataFrame 내의 데이터는 생성되는 순간 고유의 Index 값을 가지게 됨

In [27]:
# DataFrame.head()는 DataFrame의 맨 앞에 있는 N개의 로우를 반환 (default는 5개)
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [28]:
# DataFrame의 행과 열 크기를 알아보는 방법: 생성된 DataFrame 객체의 shape 변수 이용
# shape는 DataFrame의 행과 열을 튜플 형태로 반환
print('DataFrame의 크기: ',titanic_df.shape)

DataFrame의 크기:  (891, 12)

891개의 로우 & 12개의 칼럼 으로 이루어짐

DataFrame은 데이터뿐 아니라 칼럼의 타입, null 데이터 개수, 데이터 분포도 등의 메타 데이터 등도 조회 가능
- 대표적인 메서드: info(), describe()

In [29]:
# info(): 총 데이터 건수와 데이터 타입, Null 건수
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

1. RangeIndex: DataFrame index의 범위를 나타내므로 전체 row 수를 알 수 있음
2. Dtype: 칼럼별 데이터 타입
3. Non-Null Count: 몇 개의 데이터가 non-null(Null 값이 아님)인지 나타냄
4. 마지막 줄: 전체 12개의 칼럼들의 타입을 요약

In [30]:
# descirbe(): 칼럼별 숫자형 데이터값의 n-percentile 분포도, 평균값, 최댓값, 최솟값
# 오직 숫자형 칼럼의 분포도만 조사. 자동으로 object 타입의 칼럼은 출력에서 제외
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

1. count: Not Null인 데이터 건수
2. mean: 전체 데이터의 평균값
3. std: 표준편차
4. min/max: 최솟값/최댓값
5. 25% / 50% / 75% : 25 / 50 / 75 percentile

describe() 해당 숫자 칼럼이 숫자형 카테고리 칼럼인지 판단 가능


카테고리 칼럼: 특정 범주에 속하는 값을 코드화한 칼럼

Pclass 칼럼의 값이 어떠한 분포로 구성되어 있는지 살펴보기

DataFrame의 [] 연산자 내부에 칼럼명을 입력하면 Series 형태로 특정 칼럼 데이터 세트가 반환됨

반환된 Series 객체에 value_counts() 메서드를 호출하면 해당 칼럼값의 유형과 건수 확인 가능

In [31]:
# value_counts(): 지정된 칼럼의 데이터값 건수 반환. 많은 건수 순서로 정렬
# 데이터 분포도를 확인하는 데 유용한 함수
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [32]:
# DataFrame이 [] 연산자 내부에 칼럼명을 입력하면 해당 칼럼에 해당하는 Series 객체를 반환
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

Series는 index와 단 하나의 칼럼으로 구성된 데이터 세트

In [33]:
# 이렇게 반환된 Series 객체가 어떤 값으로 구성돼 있는지 알아보기
# 전체 891개의 데이터 추출X. head()로 앞의 5개만 추출
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

한 개 칼럼의 데이터만 출력되지 않고 맨 왼쪽에 0부터 시작하는 순차 값 존재: DataFrame의 인덱스와 동일한 인덱스

오른쪽: Series의 해당 칼럼의 데이터값

모든 Series와 DataFrame은 인덱스를 반드시 가짐

단일 칼럼으로 되어 있는 Series 객체에서 value_count() 메서드를 호출하는 것이 칼럼별 데이터 값의 분포도를 좀 더 명시적으로 파악하기 쉬움

In [34]:
# value_counts()를 titanic_df의 Pclass 칼럼만을 값으로 가지는 Series 객체에서 호출하여 메서드의 반환값을 다시 확인
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

value_counts()가 반환하는 데이터 타입: Series의 객체

왼쪽: 인덱스값, 오른쪽: 데이터값

인덱스는 단순히 순차 값과 같은 의미 없는 식별자만 할당하는 것이 아니라 고유성이 보장된다면 의미 있는 데이터값 할당 가능

value_counts(): 칼럼 값별 데이터 건수 반환 → 고유 칼럼 값을 식별자로 사용 가능

인덱스: DataFrame, Series가 만들어진 후에도 변경 가능. 숫자형뿐만 아니라 문자열도 가능. 모든 인덱스는 고유성이 보장돼야 함

value_counts() 메서드를 사용할 때는 Null 값을 무시하고 결괏값을 내놓기 쉬움. (유의!!)

value_countS()는 Null 값을 포함하여 개별 데이터 값의 건수를 계산할지를 dropna 인자로 판단

dropna의 기본값: True, Null 값을 무시하고 개별 데이터 값의 건수 계산

In [35]:
# 타이타닉 데이터 세트의 Embarked 칼럼의 데이터 값 분포를 value_counts()로 확인
print('titanic_df 데이터 건수: ', titanic_df.shape[0]) #타이타닉 데이터 세트의 전체 건수 확인
print('기본 설정인 dropna=True로 value_count()')

# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False)) # Null 값을 포함해서 value_counts() 적용

titanic_df 데이터 건수:  891
기본 설정인 dropna=True로 value_count()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

#### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

DataFrame
- 파이썬의 리스트, 딕셔너리, 넘파이 ndarray 등 다양한 데이터로부터 생성될 수 있음 + 변환될 수 있음
- 사이킷런의 많은 API는 DataFrame을 인자로 입력받을 수 있지만, 기본적으로 넘파이 ndarray를 입력 인자로 사용. 따라서 DataFrame과 넘파이 ndarray 상호 간의 변환은 매우 빈번하게 발생

**넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기**

DataFrame: 리스트와 넘파이 ndarray와 다르게 칼럼명을 가짐 → 편하게 데이터 핸들링 가능

DataFrame으로 변환 시 칼럼명 지정(지정하지 않으면 자동 할당)

- 판다스 DataFrame 객체의 생성 인자 data: 리스트나 딕셔너리 또는 넘파이 ndarray 입력받음

- 생성 인자 columns: 칼럼명 리스트를 입력받음

2차원 이하의 데이터들만 DataFrame으로 변환 가능

In [36]:
# 1차원 형태의 리스트, 넘파이 ndarray부터 DataFrame으로 변환
# 1차원 데이터이므로 칼럼은 1개만 필요. 칼럼명을 'col1'로 지정

import numpy as np

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape: ', array1.shape)

#리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape:  (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [37]:
# 2차원 형태의 데이터를 기반으로 DataFrame 생성
# 2행 3열 형태의 리스트와 ndarray를 기반으로 DataFrame 생성하므로 칼럼명은 3개 필요

#3개의 칼럼명이 필요함
col_name2 = ['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape: ', array2.shape)
df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape:  (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [38]:
# 딕셔너리를 DataFrame으로 변환
# 딕셔너리의 Key는 칼럼명, 값(Value)은 키에 해당하는 칼럼 데이터로 변환됨
# Key는 문자열, Value는 리스트 또는 ndarray 형태로 딕셔너리 구성

# Key는 문자열 칼럼명으로 매핑, Value는 리스트형(또는 ndarray) 칼럼 데이터로 매핑
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

**DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기**

데이터 핸들링은 DataFrame을 이용하더라도 머신러닝 패키지의 입력 인자 등에 적용하기 위해 다시 넘파이 ndarray로 변환하는 경우가 빈번하게 발생

DataFrame을 넘파이 ndarray로 변환하는 것은 DataFrame 객체의 values를 이용해 쉽게 할 수 있음 (반드시 기억해 둘 것!!)

In [39]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입: ', type(array3), 'df_dict.values shape: ', array3.shape)
print(array3)

df_dict.values 타입:  <class 'numpy.ndarray'> df_dict.values shape:  (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [40]:
# DataFrame을 리스트로 변환: values로 얻은 ndarray에 tolist() 호출
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입: ', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
# DataFrame 객체의 to_dict() 메서드 호출, 인자로 'list'를 입력하면 딕셔너리의 값이 리스트형으로 반환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입: ', type(dict3))
print(dict3)

df_dict.values.tolist() 타입:  <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입:  <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

#### DataFrame의 칼럼 데이터 세트 생성과 수정

[] 연산자 이용

In [41]:
# Titanic DataFrame의 새로운 칼럼 Age_0을 추가하고 일괄적으로 0 값 할당
titanic_df['Age_0']=0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [42]:
# 기존 칼럼 Series의 데이터를 이용해 새로운 칼럼 Series 생성
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [43]:
# DataFrame 내의 기존 칼럼 값 일괄적 업데이트
# 업데이트를 원하는 칼럼 Series를 DataFrame[] 내에 칼럼명으로 입력한 뒤에 값 할당
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

#### DataFrame 데이터 삭제

drop() 메서드 이용

원형: DataFrame.drop(labels=None, axis=0, index=None, columns=NOne, level=None, inplace=False, errors='raise')

- axis 값에 따라서 특정 칼럼/행 드롭

drop() 메서드에 axis=1을 입력하면 칼럼 축 방향으로 드롭 수행 (칼럼 드롭)
- labels에 원하는 칼럼명을 입력하고 axis=1을 입력하면 지정된 칼럼 drop
- drop() 메서드에 axis=0 입력하면 row 축 방향으로 drop 수행
- DataFrame의 특정 row를 가리키는 것은 인덱스 → axis를 0으로 지정하면 DataFrame은 자동으로 labels에 오는 값을 인덱스로 간주
- axis=1: 기존 칼럼 값을 가공해 새로운 칼럼을 만들고 삭제
- axis=0: 이상치 데이터를 삭제하는 경우에 주로 사용

In [44]:
# Titanic DataFrame에 추가된 'Age_0' 칼럼 삭제
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [45]:
# 원본 Titanic DataFrame 확인
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

inplace = False로 설정했기 때문에 삭제했다고 생각했던 'Age_0' 칼럼이 여전히 존재

inplace=false 이면 자기 자신의 DataFrame의 데이터는 삭제하지 않음. 삭제된 결과 DataFrame을 반환


titanic_df DataFrame 객체 변수는 'Age_0' 칼럼이 삭제되지 않았으며 titanic_df.drop('Age_0', axis=1)의 수행 결과로 반환된 titanic_drop_df DataFrame 객체 변수만 'Age_0' 칼럼이 삭제됨

inplace=True로 설정하면 자신의 DataFrame의 데이터 삭제

여러 개의 칼럼 삭제: 리스트 형태로 삭제하고자 하는 칼럼명 입력해 labels 파라미터로 입력

In [46]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값: ', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값:  None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

drop() 시 inplace=True로 설정하면 반환 값이 None

inplace=True로 설정한 채로 반환 값을 다시 자신의 DataFrame 객체로 할당하면 안됨

In [47]:
# axis=0으로 설정해 index 0, 1, 2 row 삭제
pd.set_option('display.width', 100)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0, 1, 2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket  \
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...

      Fare Cabin Embarked
0   7.2500   NaN        S
1  71.2833   C85        C
2   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare  \
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583

  Cabin Embarked
3  C123        S
4   NaN        S
5   NaN        Q

**drop() 메서드에서 axis와 inplace 인자를 적용해 DataFrame 변경 방식**

- axis: DataFrame의 row를 삭제할 때 axis=0, column을 삭제할 때 axis=1로 설정
- 원본 DataFrame 유지 & drop된 DataFrame을 새롭게 객체변수로 받을 때: inplace=False로 설정
- 원본 DataFrame에 drop된 결과 적용: inplace=True 적용
- 원본 DataFrame에서 drop된 DataFrame을 다시 원본 DataFrame 객체 변수로 할당하면 원본 DataFrame에서 drop된 결과를 적용할 경우와 같음

#### Index 객체
DataFrame, Series의 레코드를 고유하게 식별하는 객체

In [48]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('titanic_train.csv')

# Index 객체 추출
indexes = titanic_df.index
print(indexes)

# Index 객체를 실제 값 array로 변환
print('Index 객체 array 값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array 값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

Index 객체는 식별성 데이터를 1차원 array로 가짐

ndarray와 유사하게 단일 값 반환 및 슬라이싱 가능

In [49]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

한 번 만들어진 DataFrame 및 Series의 Index 객체는 함부로 변경 불가능

In [50]:
indexes[0]=5

TypeError: Index does not support mutable operations

Series 객체는 Index 객체 포함하지만 Series 객체에 연산 함수를 적용할 때 Index는 연산에서 제외됨

Index는 오직 식별용으로만 사용

In [51]:
series_fair = titanic_df['Fare']
print('Fair Series max 값: ', series_fair.max())
print('Fair Series sum 값: ', series_fair.sum())
print('sum() Fair Series: ', sum(series_fair))
print('Fair Series + 3:\n', (series_fair + 3).head(3))

Fair Series max 값:  512.3292
Fair Series sum 값:  28693.9493
sum() Fair Series:  28693.9493
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

DataFrame 및 Series에 reset_index() 메서드를 수행하면

새롭게 인덱스를 연속 숫자 형으로 할당, 기존 인덱스는 'index'라는 새로운 칼럼명으로 추가

In [52]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mr...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, ...",female,26.0,0,0,STON/O2. 31...,7.9250,NaN,S

reset_index(): 인덱스가 연속된 ind 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 주로 사용

Series에 reset_index()를 적용하면 Series가 아닌 DataFrame이 반환됨

→ 기존 인덱스가 column으로 추가돼 column이 2개가 되기 때문

In [53]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입: ', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입: ', type(new_value_counts))

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입:  <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입:  <class 'pandas.core.frame.DataFrame'>

Series에 reset_index()를 적용하면

새롭게 연속 숫자형 인덱스가 만들어지고 기존 인덱스는 'index' 칼럼명으로 추가되면서 DataFrame으로 변환됨

reset_index()의 parameter 중 drop=True로 설정하면

기존 인덱스는 새로운 칼럼으로 추가되지 않고 삭제(drop)됨, Series로 유지

#### 데이터 셀렉션 및 필터링
넘파이: '[]' 연산자 내 단일 값 추출, 슬라이싱, 팬시 인덱싱, 불린 인덱싱을 통해 데이터 추출

판다스: iloc[], loc[] 연산자를 통해 동일한 작업 수행

**DataFrame의 [] 연산자**

- 넘파이의 []: 행/열의 위치, 슬라이싱 범위 지정해 데이터를 가져옴
- DataFrame의 [] : 칼럼 지정 연산자

DataFrame 바로 뒤에 있는 '[]' 안에 들어갈 수 있는 것은 칼럼명 문자(또는 칼럼명의 리스트 객체) 또는 인덱스로 변환 가능한 표현식

In [54]:
# DataFrame에 ['칼럼명']으로 '칼럼명'에 해당하는 칼럼 데이터의 일부만 추출
# 여러 개의 칼럼에서 데이터 추출: ['칼럼1', '칼럼2'] 리스트 객체 이용

print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))
print('[] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

In [55]:
# 판다스의 인덱스 형태로 변환 가능한 표현식은 [] 내에 입력 가능
# titanic_df의 처음 2개 데이터를 추출
titanic_df[0:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mr...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [56]:
# 불린 인덱싱 표현
# Pclass 칼럼 값이 3인 데이터 3개 추출
titanic_df[titanic_df['Pclass'] == 3].head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, ...",female,26.0,0,0,STON/O2. 31...,7.925,NaN,S
4,5,0,3,"Allen, Mr. ...",male,35.0,0,0,373450,8.050,NaN,S

**DataFrame 뒤의 [] 연산자의 입력 인자 혼동 방지**

- DataFrame 바로 뒤의 [] 연산자는 넘파이의 []나 Series의 []와 다름
- DataFrame 바로 뒤의 [] 내 입력값은 칼럼명(또는 칼럼의 리스트)을 지정해 칼럼 지정 연산에 사용 / 불린 인덱스 용도로만 사용
- DataFrame[0:2]와 같은 슬라이싱 연산으로 데이터를 추출하는 방법은 지양

#### DataFrame iloc[] 연산자
row나 column을 지정하여 데이터를 선택할 수 있는 인덱싱 방식

location 기반 인덱싱 방식으로 동작
- loc[]: 명칭(label) 기반 인덱싱 방식

- 위치 기반 인덱싱: 행열 위치를, 0을 출발점으로 하는 세로축, 가로축 좌표 정숫값으로 지정하는 방식
- 명칭 기반 인덱싱: 데이터 프레임의 인덱스 값으로 행 위치를, 칼럼의 명칭으로 열 위치를 지정하는 방식

iloc[]

행열의 좌표 위치에 해당하는 값으로 정숫값/정수형의 슬라이싱, 팬시 리스트 값을 입력

In [57]:
# 생성한 DataFrame은 인덱스 값으로 숫자값이 아닌 문자열로 'one', 'two', 'three', 'four' 가짐
# Name, Year, Gender 3개의 칼럼을 가짐

data = {'Name': ['Chulmin', 'Eunkyung', 'JInwoong', 'Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
}
data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  JInwoong  2015    Male
four    Soobeom  2015    Male

In [58]:
# data_df의 첫 번째 행, 첫 번째 열의 데이터를 iloc[]를 이용해 추출
data_df.iloc[0, 0]

'Chulmin'

iloc[행 위치 정숫값, 열 위치 정숫값]과 같이 명확하게 DataFrame의 행 위치와 열 위치를 좌표 정숫값 형태로 입력하여 해당 위치에 있는 데이터를 가져올 수 있음

In [60]:
# iloc[]에 DataFrame의 인덱스 값이나 칼럼명을 입력하면 오류 발생

# iloc[]의 열 위치에 위치 정숫값이 아닌 칼럼 명칭을 입력하여 오류 발생
data_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [61]:
# iloc[]의 행 위치에 DataFrame의 인덱스 값인 'one'을 입력하여 오류 발생
data_df.iloc['one', 0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

- data_df.iloc[1, 0]: 두번째 행의 첫번째 열 위치에 있는 단일 값 반환
- data_df.iloc[2, 1]: 세번째 행의 두번째 열 위치에 있는 단일 값 반환
- data_df.iloc[0:2, [0,1]]: 0:2 슬라이싱 범위의 첫번째에서 두번째 행과 첫번째, 두번째 열에 해당하는 DataFrame 반환
- data_df.iloc[0:2, 0:3]: 0:2 슬라이싱 범위의 첫번째에서 두번째 행의 0:3 슬라이싱 범위의 첫번째부터 세번째 열 범위에 해당하는 DataFrame 반환
- data_df.iloc[:]: 전체 DataFrame 반환
- data_df.iloc[:,:]: 전체 DataFrame 반환

iloc[]: 열 위치에 -1을 입력하여 DataFrame의 가장 마지막 열 데이터를 가져오는 데 사용

In [62]:
print("\n 맨 마지막 칼럼 데이터 [:, -1]\n", data_df.iloc[:, -1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1]\n", data_df.iloc[:, :-1])

 맨 마지막 칼럼 데이터 [:, -1]
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1]
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  JInwoong  2015
four    Soobeom  2015

#### DataFrame lov[] 연산자

loc[]: 명칭(Label) 기반으로 데이터를 추출

행 위치에는 DataFrame 인덱스 값, 열 위치에는 칼럼명 입력 → loc[인덱스값, 칼럼명]와 같은 형식으로 데이터 추출

In [63]:
# 인덱스의 값이 'one'인 행의 칼럼명이 'Name'인 데이터 추출
data_df.loc['one', 'Name']

'Chulmin'

일반적으로 인덱스는 0부터 시작하는 정숫값인 경우가 많기 때문에 실제 인덱스 값을 확인하지 않고 loc[]의 행 위치에 무턱대고 정숫값을 입력해서 오류가 나는 경우가 발생

In [64]:
# 첫번째 행 위치의 인덱스 값을 0으로 착각하고 행 위치에 0을 입력했지만 data_df는 0을 인덱스 값으로 가지고 있지 않음
data_df.loc[0, 'Name']

KeyError: 0

** loc[]에 슬라이싱 기호 ':'를 적용할 때 유의할 점

슬라이싱 기호 적용 시 종료값 -1이 아니라 종료값까지 포함 (명칭은 숫자형이 아니기 때문)

In [65]:
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0], '\n')
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name'])

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

**loc[] 연산의 다양한 수행 사례**
- data_df.loc['three', 'Name']: 인덱스 값 three인 행의 Name 칼럼의 단일값 반환
- data_df.loc['one':'two', ['Name', 'Year']]: 인덱스 값 one부터 two까지 행의 Name과 Year 칼럼에 해당하는 DataFrame 반환
- data_df.loc['one':'three', 'Name':'Gender']: 인덱스 값 one부터 three까지 행의 Name부터 Gender 칼럼까지의 DataFrame 반환
- data_df.loc[:]: 모든 데이터 값
- data_df.loc[data_df.Year>=2014]: iloc[]와 다르게 loc[]는 불린 인덱싱이 가능. Year 칼럼의 값이 2014 이상인 모든 데이터를 불린 인덱싱으로 추출

**[], iloc[], loc[]의 특징 & 주의할 점**
- 개별 또는 여러 칼럼 값 전체를 추출하고자 한다면 iloc[]나 loc[]를 사용하지 않고 data_df['Name']과 같이 DataFrame['칼럼명']만으로 충분. 하지만 행과 열을 함께 사용하여 데이터를 추출해야 한다면 iloc[]나 loc[] 사용
- iloc[]와 loc[]를 이해하기 위해서는 명칭 기반 인덱싱과 위치 기반 인덱싱의 차이 이해. DataFrame의 인덱스나 칼럼명으로 데이터에 접근하는 것은 명칭 기반 인덱싱. 0부터 시작하는 행, 열의 위치 좌표에만 의존하는 것이 위치 기반 인덱싱
- iloc[]는 위치 기반 인덱싱만 가능. 따라서 행과 열 위치 값으로 정수형 값을 지정해 원하는 데이터를 반환
- loc[]는 명칭 기반 인덱싱만 가능. 따라서 행 위치에 DataFrame 인덱스가 오며, 열 위치에는 칼럼명을 지정해 원하는 데이터를 반환
- 명칭 기반 인덱싱에서 슬라이싱을 '시작점:종료점'으로 지정할 때 시작점에서 종료점을 포함한 위치에 있는 데이터 반환

**불린 인덱싱**

[], loc[]에서 공통으로 지원

iloc[]는 정수형 값이 아닌 불린 값에 대해서는 지원하지 않기 때문에 불린 인덱싱이 지원되지 않음

In [66]:
# 새롭게 타이타닉 데이터 세트를 DataFrame으로 로드
# 승객 중 나이가 60세 이상인 데이터 추출
# 연산자 내에 불린 조건을 입력하면 불린 인덱싱으로 자동으로 결과를 찾아줌

titanic_df = pd.read_csv('titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr...",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. ...",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,Goldschmidt...,male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr...",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,Van der hoe...,male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. ...",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. ...",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr...",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr...",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr....",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mr...",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,Artagaveyti...,male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, ...",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr....",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr....",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr....",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, ...",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, M...",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Cap...",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, M...",male,74.0,0,0,347060,7.7750,NaN,S

[] 내에 불린 인덱싱을 적용하면

반환되는 객체가 DataFrame이므로 원하는 칼럼명만 별도로 추출 가능

In [67]:
# 60세 이상인 승객의 나이와 이름만 추출
# []연산자에 칼럼명 입력
titanic_df[titanic_df['Age']>60][['Name', 'Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [68]:
# loc[]를 이용해도 동일하게 적용 가능, ['Name', 'Age']는 칼럼 위치에 놓여야함
titanic_df.loc[titanic_df['Age']>60, ['Name', 'Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

- and: &
- or: |
- Not: ~

In [69]:
# 개별 조건은 ()로 묶고, 복합 조건 연산자 사용
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&
           (titanic_df['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN

In [70]:
# 개별 조건을 변수에 할당하고 이들 변수를 결합해서 불린 인덱싱을 수행
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN

#### 정렬, Aggregation 함수, GroupBy 적용
**DataFrame, Series의 정렬 - sort_values()**

sort_values()
- 주요 입력 파라미터: by, ascending, inplace
- by로 특정 칼럼을 입력하면, 해당 칼럼으로 정렬 수행
- ascending = True로 설정하면, 오름차순으로 정렬 (기본)
- ascending = False로 설정하면, 내림차순으로 정렬
- inplace = False로 설정하면, sort_values()를 호출한 DataFrame은 그대로 유지하며 정렬된 DataFrame을 결과로 반환 (기본)
- inplace = True로 설정하면, 호출한 DataFrame의 정렬 결과를 그대로 적용

In [71]:
# titanic_df를 Name 칼럼으로 오름차순 정렬
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr....",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr....",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs...",female,35.0,1,1,C.A. 2673,20.25,NaN,S

여러 개 칼럼으로 정렬하려면 by에 리스트 형식으로 정렬하려는 칼럼 입력

In [72]:
# Pclass와 Name를 내림차순으로 정렬
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending = False)
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
868,869,0,3,van Melkebe...,male,NaN,0,0,345777,9.5,NaN,S
153,154,0,3,van Billiar...,male,40.5,0,2,A/5. 851,14.5,NaN,S
282,283,0,3,de Pelsmaek...,male,16.0,0,0,345778,9.5,NaN,S

**Aggregation 함수 적용**

min(), max(), sum(), count() 등

DataFrame에서 바로 aggregation을 호출할 경우 모든 칼럼에 해당 aggregation을 적용
- count()는 Null 값을 반영하지 않은 결과를 반환하므로 NULL 값이 있는 칼럼은 count()의 결과값이 다름

In [74]:
# count() 적용 시 모든 칼럼에 count() 결과 반환 (Null 값을 반영 X)
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [75]:
# 특정 칼럼에 aggregation 함수 적용 위해서는 DataFrame에 대상 칼럼들만 추출해 aggregation 적용
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

**groupby() 적용**

SQL과 판다스 모두 groupby를 분석 작업에 많이 활용

DataFrame이 groupby() 사용 시 입력 파라미터 by에 칼럼을 입력하면 대상 칼럼으로 groupby

DataFrame에 groupby()를 호출하면 DataFrameGroupBy라는 또 다른 형태의 DataFrame 반환

In [76]:
# Pclass 칼럼 기준으로 GroupBy된 DataFrameGoupby 객체 반환
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

DataFrame에 groupby()를 호출해 반환된 결과에 aggregation 함수를 호출하면 groupby() 대상 칼럼을 제외한 모든 칼럼에 해당 aggregation 함수 적용

In [77]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

DataFrame의 groupby()에 특정 칼럼만 aggregation 함수를 적용하려면 groupby()로 반환된 DataFrameGroupBy 객체에 해당 칼럼을 필터링한 뒤 aggregation 함수를 적용

In [78]:
# titanic_df.groupby('Pclass')로 반환된 DataFrameGroupBy 객체에 [['PassengerId', 'Survived']]로 필터링해 PassengerId와 Survived 칼럼에만 count() 수행
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

DataFrame groupby()의 경우 적용하려는 여러 개의 aggregation 함수명을 DataFrameGroupBy 객체의 agg() 내에 인자로 입력해서 사용

In [79]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

/tmp/ipykernel_443/1565262784.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])
/tmp/ipykernel_443/1565262784.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

여러 개의 칼럼이 서로 다른 aggregation 함수를 groupby에서 호출하려면 DataFrame groupby()는 좀 더 복잡한 처리가 필요함

groupby()는 agg()를 이용해 이 같은 처리가 가능

agg() 내에 입력값으로 딕셔너리 형태로 aggregation이 적용될 칼럼들과 aggregation 함수 입력

In [80]:
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

#### 결손 데이터 처리하기
- 결손 데이터: 칼럼에 값이 없는 NULL인 경우를 의미, 넘파이의 NaN으로 표시

머신러닝 알고리즘은 NaN 값을 처리하지 않으므로 이 값을 다른 값을 대체해야 함, 함수 연산 시 제외

- NaN 여부를 확인하는 API: isna()
- NaN 값을 다른 값으로 대체하는 API: fillna()

**isna()로 결손 데이터 여부 확인**

데이터가 NaN인지 아닌지 알려줌

DataFrame에 isna()를 수행하면 모든 칼럼의 값이 NaN인지 아닌지를 True/False로 알려줌

In [81]:
titanic_df.isna().head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False

결손 데이터의 개수는 isna() 결과에 sum() 함수를 추가해 구할 수 있음

sum() 호출 시 True는 1로 False는 0으로 변환

In [82]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**fillna()로 결손 데이터 대체하기**

fillna()로 결손 데이터를 편리하게 다른 값으로 대체

In [83]:
# 타이타닉 데이터 세트의 'Cabin' 칼럼의 NaN 값을 'C000'으로 대체
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.2500,C000,S
1,2,1,1,"Cumings, Mr...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, ...",female,26.0,0,0,STON/O2. 31...,7.9250,C000,S

fillna()를 이용해 반환 값을 다시 받거나 inplace=True 파라미터를 fillna()에 추가해야 실제 데이터 세트 값이 변경됨

fillna() 반환 값을 다시 titanic_df['Cabin']로 정해주거나 반환 변숫값을 지정하지 않으려면 inplace=True를 설정해야함

In [84]:
# 'Age' 칼럼의 NaN 값을 평균 나이로, 'Embarked' 칼럼의 NaN 값을 'S'로 대체해서 모든 결손 데이터를 처리
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

**apply lambda 식으로 데이터 가공**

aplly 함수에 lambda 식을 결합해 DataFrame이나 Series의 레코드별로 데이터 가공하는 기능 제공
- lambda: 파이썬에서 함수형 프로그래밍을 지원하기 위해 만들어짐

In [86]:
# 입력값의 제곱 값을 구해서 반환하는 get_square(a)라는 함수
def get_square(a):
  return a**2

print('3의 제곱은: ', get_square(3))

3의 제곱은:  9

위의 함수: def get_square(a):와 같은 함수명과 입력 인자를 먼저 선언하고 이후 함수 내에서 입력 인자를 가공한 뒤 결괏값을 return과 같은 문법으로 반환

lambda는 이런 함수의 선언과 함수 내의 처리를 한 줄의 식으로 쉽게 변환

In [87]:
lambda_square = lambda x : x**2
print('3의 제곱은: ', lambda_square(3))

3의 제곱은:  9

lambda x : x**2에서 ':'로 입력 인자와 반환될 입력 인자의 계산식 분리

오른쪽의 계산식: 반환 값을 의미

In [88]:
# lambda 식을 이용할 때 여러 개의 값을 입력 인자로 사용해야 할 경우에는 map() 함수를 결합
a=[1, 2, 3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [89]:
# DataFrame의 apply에 lambda 식을 적용해 데이터 가공
# 'Name' 칼럼의 문자열 개수를 별도의 칼럼인 'Name_len'에 생성
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [90]:
# lambda 식에서 if else 절을 사용해 가공

# 나이가 15세 미만이면 'Child', 그렇지 않으면 'Adult'로 구분하는 새로운 칼럼 'Child_Adult'
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

lambda 식은 if else를 지원하지만

**주의할 점
- if 절의 경우 if 식보다 반환 값을 먼저 기술 (lambda 식 ':' 기호의 오른편에 반환값이 있어야 하기 때문)
- else의 경우 else 식이 먼저 나오고 반환값이 나중에 오면 됨
- if, else만 지원 / else if는 지원하지 않음
- else if를 이용하기 위해서는 else 절을 ()로 내포해 () 내에서 다시 if else 적용해 사용

In [91]:
# 나이가 15세 이하이면 Child, 15~60세 사이는 Adult, 61세 이상은 Elderly로 분류하는 'Age_Cat' 칼럼
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

else if가 많이 나와야 하는 경우나 switch case 문의 경우는 별도의 함수를 만드는 게 낫다

In [92]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age):
  cat = ''
  if age <=5: cat = 'Baby'
  elif age <= 12: cat = 'Child'
  elif age <= 18: cat = 'Teenager'
  elif age <= 25: cat = 'Student'
  elif age <= 35: cat = 'Young Adult'
  elif age <= 60: cat = 'Adult'
  else: cat = 'Elderly'

  return cat

# lambda 식에 위에서 생성한 get_category() 함수를 반환값으로 지정
# get_category(X)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age', 'Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult

#### 정리

넘파이와 판다스는 머신러닝 학습을 위해 정복해야 할 매우 중요한 요소.

실제로 ML 모델을 생성하고 예측을 수행하는 데 있어서 ML 알고리즘이 차지하는 비중보다 데이터를 전처리하고 적절한 피처를 가공/추출하는 부분이 훨씬 많은 비중을 차지하게 된다. 따라서 바로 뒤에서 설명할 사이킷런에 대한 이해도 중요하지만, 넘파이, 판다스, 맷플롯립/시본과 같이 파이썬 머신러닝 생태계를 이루고 있는 다양한 패키지에 대한 이해 역시 매우 중요하다.