<a href="https://colab.research.google.com/github/tustus1022-ui/esaa/blob/main/%EC%B5%9C%EC%A2%85_Numerai_validation_diagnostics_%EC%9C%A0%EB%AF%BC%EC%A3%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numerapi -q

import numerapi
import getpass

NUMERAI_PUBLIC_ID = getpass.getpass("Public ID 입력: ").strip()
NUMERAI_SECRET_KEY = getpass.getpass("Secret Key 입력: ").strip()

napi = numerapi.NumerAPI(public_id=NUMERAI_PUBLIC_ID, secret_key=NUMERAI_SECRET_KEY)
print(napi.get_models())

Public ID 입력: ··········
Secret Key 입력: ··········
{'mjyu': '1e697cd9-10dd-4d58-af38-384b23d45fa2', 'ensemble1_5models': '749c4960-06fb-452f-910e-890bc3e3d4b1', 'ensemble2_3models': '7a126b9b-f060-42be-bedb-bcf7725a644a', 'ensemble3_lineartree': 'a7e176ad-e868-4228-86d9-4d17d2824a51', 'ensemble4_all': 'f5b2f61d-8432-4e02-a576-e5208135cc15'}

## Ensemble1: XGBoost CatBoost LightGBM ExtraTrees RandomForest

In [ ]:
models = napi.get_models()

model_id_ensemble1 = models["ensemble1_5models"]

status_ensemble1 = napi.diagnostics(
    model_id=model_id_ensemble1)

print(type(status_ensemble1))
print(status_ensemble1)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_ensemble1:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.6734522786308199
validationCorrMean: 0.03598828358077405
validationCorrStd: 0.05343850592345012
validationFeatureNeutralCorrV3Mean: 0.031804135254183304
validationBmcMean: -0.013196167738638163
validationFeatureCorrMax: 0.66053959629803
validationMaxDrawdown: -0.4798933086696593
validationAutocorr: 0.06188523595855938
validationCorrCorrWExamplePreds: None
status: done
validationCorrSharpe: 0.9673948664356447
validationCorrMean: 0.015001485676045955
validationCorrStd: 0.015507096632958947
validationFeatureNeutralCorrV3Mean: 0.013790073782404478
validationBmcMean: -0.0021952601186527028
validationFeatureCorrMax: 0.32440420452895535
validationMaxDrawdown: -0.18865196962500796
validationAutocorr: 0.28786984430292206
validationCorrCorrWExamplePreds: None

In [ ]:
import pandas as pd

diagnostics_df = pd.DataFrame(status_ensemble1)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,None,done,0.031804,649,False,429.405620,2026-07-21T10:34:22Z,0.035988,-0.479893,0.788054,0.061885,2.171056,0.673452,-0.013196,0.053439,0.660540,"[{'era': '575', 'examplePredsCorr': 0.82415187..."
1,valid,done,0.013790,649,False,106.244766,2026-07-21T10:34:22Z,0.015001,-0.188652,0.466092,0.287870,1.141389,0.967395,-0.002195,0.015507,0.324404,"[{'era': '575', 'examplePredsCorr': 0.50372253..."

## Ensemble2: XGBoost CatBoost LightGBM

In [ ]:
models = napi.get_models()

model_id_ensemble2 = models["ensemble2_3models"]

status_ensemble2 = napi.diagnostics(
    model_id=model_id_ensemble2)

print(type(status_ensemble2))
print(status_ensemble2)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_ensemble2:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.6559903904003179
validationCorrMean: 0.03503703478907814
validationCorrStd: 0.05341089641221238
validationFeatureNeutralCorrV3Mean: 0.03011515561362282
validationBmcMean: -0.012883562522577491
validationFeatureCorrMax: 0.5631494095835669
validationMaxDrawdown: -0.5998527306506105
validationAutocorr: 0.05674312519920853
validationCorrCorrWExamplePreds: None
status: done
validationCorrSharpe: 0.9708340639719324
validationCorrMean: 0.015236370532542367
validationCorrStd: 0.015694103758789064
validationFeatureNeutralCorrV3Mean: 0.013486172158431535
validationBmcMean: -0.0018892936272363117
validationFeatureCorrMax: 0.27105946090094846
validationMaxDrawdown: -0.2009605820430984
validationAutocorr: 0.29514465406038315
validationCorrCorrWExamplePreds: None

In [ ]:
diagnostics_df = pd.DataFrame(status_ensemble2)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,None,done,0.030115,649,False,406.233059,2026-07-21T10:35:33Z,0.035037,-0.599853,0.786866,0.056743,2.111188,0.655990,-0.012884,0.053411,0.563149,"[{'era': '575', 'examplePredsCorr': 0.81685415..."
1,valid,done,0.013486,649,False,108.569601,2026-07-21T10:35:33Z,0.015236,-0.200961,0.460773,0.295145,1.202496,0.970834,-0.001889,0.015694,0.271059,"[{'era': '575', 'examplePredsCorr': 0.49906185..."

## Ensemble3: Ridge ElasticNet XGBoost ExtraTrees Catboost

In [ ]:
models = napi.get_models()

model_id_ensemble3 = models["ensemble3_lineartree"]

status_ensemble3 = napi.diagnostics(
    model_id=model_id_ensemble3)

print(type(status_ensemble3))
print(status_ensemble3)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_ensemble3:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.7068511157491644
validationCorrMean: 0.03688821467538242
validationCorrStd: 0.052186682391080354
validationFeatureNeutralCorrV3Mean: 0.03363208900915356
validationBmcMean: -0.011210949833700511
validationFeatureCorrMax: 0.6659064106537069
validationMaxDrawdown: -0.58295358296564
validationAutocorr: 0.10297269460455105
validationCorrCorrWExamplePreds: None
status: done
validationCorrSharpe: 0.9788041236637054
validationCorrMean: 0.015411170382987427
validationCorrStd: 0.015744897278632992
validationFeatureNeutralCorrV3Mean: 0.014170328553892933
validationBmcMean: -0.002828934083892301
validationFeatureCorrMax: 0.32673704434781276
validationMaxDrawdown: -0.1642262028418262
validationAutocorr: 0.29091326597408473
validationCorrCorrWExamplePreds: None

In [ ]:
diagnostics_df = pd.DataFrame(status_ensemble3)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,None,done,0.033632,649,False,454.532019,2026-07-21T10:35:35Z,0.036888,-0.582954,0.811839,0.102973,2.474201,0.706851,-0.011211,0.052187,0.665906,"[{'era': '575', 'examplePredsCorr': 0.85151382..."
1,valid,done,0.014170,649,False,110.329811,2026-07-21T10:35:35Z,0.015411,-0.164226,0.496095,0.290913,1.290061,0.978804,-0.002829,0.015745,0.326737,"[{'era': '575', 'examplePredsCorr': 0.55611808..."

## Ensemble4: Ridge ElasticNet XGBoost ExtraTrees CatBoost RandomForest LightGBM

In [ ]:
models = napi.get_models()

model_id_ensemble4 = models["ensemble4_all"]

status_ensemble4 = napi.diagnostics(
    model_id=model_id_ensemble4)

print(type(status_ensemble4))
print(status_ensemble4)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_ensemble4:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.7160706248085636
validationCorrMean: 0.03790207044612995
validationCorrStd: 0.052930631606711694
validationFeatureNeutralCorrV3Mean: 0.03331845948281727
validationBmcMean: -0.012322946926820504
validationFeatureCorrMax: 0.6767942995083431
validationMaxDrawdown: -0.5121677104093898
validationAutocorr: 0.07473765644124847
validationCorrCorrWExamplePreds: None
status: done
validationCorrSharpe: 0.9878028913528445
validationCorrMean: 0.015656515003855266
validationCorrStd: 0.015849837190102675
validationFeatureNeutralCorrV3Mean: 0.0144583340199953
validationBmcMean: -0.002642924592351812
validationFeatureCorrMax: 0.33364012161462436
validationMaxDrawdown: -0.17598107156390874
validationAutocorr: 0.2967200517391203
validationCorrCorrWExamplePreds: None

In [ ]:
diagnostics_df = pd.DataFrame(status_ensemble4)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,None,done,0.033318,649,False,480.772590,2026-07-21T10:36:05Z,0.037902,-0.512168,0.812342,0.074738,2.536088,0.716071,-0.012323,0.052931,0.676794,"[{'era': '575', 'examplePredsCorr': 0.84832233..."
1,valid,done,0.014458,649,False,112.817751,2026-07-21T10:36:04Z,0.015657,-0.175981,0.496182,0.296720,1.348747,0.987803,-0.002643,0.015850,0.333640,"[{'era': '575', 'examplePredsCorr': 0.55032427..."