<a href="https://colab.research.google.com/github/tustus1022-ui/esaa/blob/main/%EC%B5%9C%EC%A2%85_Numerai_Validation_Diagnostics_%EB%AF%BC%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

주연님이 주신 메타 모델로 학습한걸로 전부 다시 다 돌려본 결과, 주연님 메타 모델 결과가 나아서 그걸로 전부 수정했습니다

In [ ]:
!pip install numerapi -q

import numerapi
import getpass

NUMERAI_PUBLIC_ID = getpass.getpass("Public ID 입력: ").strip()
NUMERAI_SECRET_KEY = getpass.getpass("Secret Key 입력: ").strip()

napi = numerapi.NumerAPI(public_id=NUMERAI_PUBLIC_ID, secret_key=NUMERAI_SECRET_KEY)
print(napi.get_models())

Public ID 입력: ··········
Secret Key 입력: ··········
{'ridge_elastic': 'fdc5792c-c55b-4fa3-8093-a9d84b326296', 'ridge_elastic_xg': 'e7d220e1-534c-4afa-94a0-973deb35be3a', 'ridge_xgboost_cat': 'e5534a88-3947-42a9-a3e1-9cc6d5c66137', 'ridge_elastic_fixed': '6b86707e-1cee-4e5b-8a92-784b05223231', 'elastic_rf_et': '2f34e5d5-7c5e-49f2-9ad9-877ca08b9a99', 'ridge_el_xg_fixed': 'b3727428-a300-457b-9c08-97ee6398efea', 'ridge_xg_cat_fixed': '1e9e0c42-6aa0-4bcc-bed8-9a5b98d1fb5f'}

## Ridge Elastic (Fixed Version)

https://github.com/smichelle0804/26-1-ESAA_Numerai-/blob/main/numerai_ridge_elastic_ver2.ipynb

In [ ]:
models = napi.get_models()

model_id_ridge_elastic_fixed = models["ridge_elastic_fixed"]
diagnostics_id_ridge_elastic_fixed = "e22c1217-b39f-471f-a4d9-bb08505d4e35"

status_ridge_elastic_fixed = napi.diagnostics(
    model_id=model_id_ridge_elastic_fixed,
    diagnostics_id=diagnostics_id_ridge_elastic_fixed,
)

print(type(status_ridge_elastic_fixed))
print(status_ridge_elastic_fixed)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_ridge_elastic_fixed:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.6693570779104576
validationCorrMean: 0.00962278258775174
validationCorrStd: 0.014376157219090488
validationFeatureNeutralCorrV3Mean: 0.008974857670511743
validationBmcMean: -0.0016973269075122109
validationFeatureCorrMax: 0.20536075207486232
validationMaxDrawdown: -0.366937336828701
validationAutocorr: 0.22511012236797356
validationCorrCorrWExamplePreds: None

In [ ]:
diagnostics_df = pd.DataFrame(status_ridge_elastic_fixed)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,valid,done,0.008975,649,False,59.088442,2026-07-20T03:54:21Z,0.009623,-0.366937,0.31469,0.22511,-0.189131,0.669357,-0.001697,0.014376,0.205361,"[{'era': '575', 'examplePredsCorr': 0.34888893..."

## Ridge Elastic XGboost (Fixed Version)

https://github.com/smichelle0804/26-1-ESAA_Numerai-/blob/main/numerai_ridge_elasticnet_xgboost_ver2.ipynb

In [ ]:
models = napi.get_models()

model_id_ridge_elastic_fixed = models["ridge_el_xg_fixed"]
diagnostics_id_ridge_elastic_fixed = "b5f3e9bc-230e-47ce-abcf-99c603efe69d"

status_ridge_elastic_xg_fixed = napi.diagnostics(
    model_id=model_id_ridge_elastic_fixed,
    diagnostics_id=diagnostics_id_ridge_elastic_fixed,
)

print(type(status_ridge_elastic_xg_fixed))
print(status_ridge_elastic_xg_fixed)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_ridge_elastic_xg_fixed:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.8621882692273257
validationCorrMean: 0.013309114543332442
validationCorrStd: 0.015436436586245576
validationFeatureNeutralCorrV3Mean: 0.011983446948226324
validationBmcMean: -0.0018942181407365483
validationFeatureCorrMax: 0.25623236815920053
validationMaxDrawdown: -0.1807872369812369
validationAutocorr: 0.30774357520528134
validationCorrCorrWExamplePreds: None

In [ ]:
diagnostics_df = pd.DataFrame(status_ridge_elastic_xg_fixed)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,valid,done,0.011983,649,False,90.058065,2026-07-20T06:08:27Z,0.013309,-0.180787,0.411572,0.307744,0.680377,0.862188,-0.001894,0.015436,0.256232,"[{'era': '575', 'examplePredsCorr': 0.46470020..."

## Ridge XGboost Catboost (Fixed Version)

https://github.com/smichelle0804/26-1-ESAA_Numerai-/blob/main/numeraI_ridge_xgboost_catboost_ver2.ipynb

In [ ]:
models = napi.get_models()

model_id_ridge_elastic = models["ridge_xg_cat_fixed"]
diagnostics_id_ridge_elastic = "1b85ffa7-e7b8-4a89-beb5-a401a90bf3ed"

status_ridge_xgboost_cat = napi.diagnostics(
    model_id=model_id_ridge_elastic,
    diagnostics_id=diagnostics_id_ridge_elastic,
)

print(type(status_ridge_xgboost_cat))
print(status_ridge_xgboost_cat)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_ridge_xgboost_cat:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.9422359995998866
validationCorrMean: 0.014808469155972644
validationCorrStd: 0.015716305853587582
validationFeatureNeutralCorrV3Mean: 0.013284162855130325
validationBmcMean: -0.002121592478307776
validationFeatureCorrMax: 0.279129434105996
validationMaxDrawdown: -0.17364903878640625
validationAutocorr: 0.3054924703979741
validationCorrCorrWExamplePreds: None

In [ ]:
import pandas as pd
diagnostics_df = pd.DataFrame(status_ridge_xgboost_cat)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,valid,done,0.013284,649,False,104.301148,2026-07-20T06:15:22Z,0.014808,-0.173649,0.462569,0.305492,1.088491,0.942236,-0.002122,0.015716,0.279129,"[{'era': '575', 'examplePredsCorr': 0.51578191..."

## Elastic RandomForest ExtraTrees

https://github.com/smichelle0804/26-1-ESAA_Numerai-/blob/main/numerai_elasticnet_extratrees_randomforest_ver2.ipynb

In [ ]:
models = napi.get_models()

model_id_elastic_rf_et = models["elastic_rf_et"]
diagnostics_id_elastic_rf_et = "4e9691f6-826c-4293-8b0d-fb9a9df3495d"

status_elastic_rf_et = napi.diagnostics(
    model_id=model_id_elastic_rf_et,
    diagnostics_id=diagnostics_id_elastic_rf_et,
)

print(type(status_elastic_rf_et))
print(status_elastic_rf_et)

<class 'list'>

In [ ]:
key_fields = [
    "status",
    "validationCorrSharpe",
    "validationCorrMean",
    "validationCorrStd",
    "validationFeatureNeutralCorrV3Mean",
    "validationBmcMean",
    "validationFeatureCorrMax",
    "validationMaxDrawdown",
    "validationAutocorr",
    "validationCorrCorrWExamplePreds",
]

for item in status_elastic_rf_et:
    for k in key_fields:
        if k in item:
            print(f"{k}: {item[k]}")

status: done
validationCorrSharpe: 0.9058909264477488
validationCorrMean: 0.013953073124011178
validationCorrStd: 0.01540259728478027
validationFeatureNeutralCorrV3Mean: 0.013331568672791989
validationBmcMean: -0.0025765043375634215
validationFeatureCorrMax: 0.34732406892794365
validationMaxDrawdown: -0.23988273461737997
validationAutocorr: 0.2857673097897672
validationCorrCorrWExamplePreds: None

In [ ]:
import pandas as pd
diagnostics_df = pd.DataFrame(status_elastic_rf_et)
diagnostics_df = diagnostics_df.dropna(axis=1, how="all")
display(diagnostics_df)

,message,status,validationFeatureNeutralCorrV3Mean,erasAcceptedCount,trainedOnVal,validationApy,updatedAt,validationCorrMean,validationMaxDrawdown,examplePredsCorrMean,validationAutocorr,validationAdjustedSharpe,validationCorrSharpe,validationBmcMean,validationCorrStd,validationFeatureCorrMax,perEraDiagnostics
0,valid,done,0.013332,649,False,96.073697,2026-07-20T05:39:13Z,0.013953,-0.239883,0.458262,0.285767,0.859435,0.905891,-0.002577,0.015403,0.347324,"[{'era': '575', 'examplePredsCorr': 0.50209664..."